# Generated by Django 5.1.6 on 2025-05-08 08:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colormodel',
            options={'ordering': ['color'], 'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
        migrations.AddField(
            model_name='colormodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='colormodel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='color',
            field=models.CharField(help_text='Enter the name of the color (e.g., Sky Blue, Olive Green).', max_length=50, unique=True, verbose_name='Color Name'),
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to='file'),
        ),
    ]
