# Generated by Django 5.1.6 on 2025-03-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_filemodel_file_alter_imagemodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
