# Generated by Django 5.1.6 on 2025-05-08 08:07

import accounts.models
import core.filepath
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='is_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryboymodel',
            name='is_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellermodel',
            name='is_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='customer_rank',
            field=models.CharField(choices=[('1', 'Noob')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryboymodel',
            name='delivery_boy_rank',
            field=models.CharField(choices=[('1', 'Noob')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='deliveryboymodel',
            name='file_license',
            field=models.FileField(blank=True, null=True, upload_to=core.filepath.hash_license),
        ),
        migrations.AlterField(
            model_name='deliveryboymodel',
            name='license_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='deliveryboymodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveryboy_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='GST_expiry_date',
            field=models.DateField(default=accounts.models.default_gst_expiry),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='file_gst',
            field=models.FileField(blank=True, null=True, upload_to=core.filepath.hash_document),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='file_pan',
            field=models.FileField(blank=True, null=True, upload_to=core.filepath.hash_document),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='seller_rank',
            field=models.CharField(choices=[('1', 'Noob')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='shop_address_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='shop_address_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='shop_landmark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermanagementmodel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagementmodel',
            name='district',
            field=models.CharField(blank=True, choices=[('AR', 'Ariyalur'), ('CH', 'Chennai'), ('CO', 'Coimbatore'), ('CU', 'Cuddalore'), ('DH', 'Dharmapuri'), ('DI', 'Dindigul'), ('EK', 'Erode'), ('KA', 'Kallakurichi'), ('KA2', 'Kancheepuram'), ('KA3', 'Kanniyakumari'), ('KA4', 'Karur'), ('KR', 'Krishnagiri'), ('MA', 'Madurai'), ('NA', 'Nagapattinam'), ('NI', 'Nilgiris'), ('PE', 'Perambalur'), ('PU', 'Pudukkottai'), ('RA', 'Ramanathapuram'), ('SA', 'Salem'), ('SI', 'Sivaganga'), ('TE', 'Tenkasi'), ('TH', 'Thanjavur'), ('TH2', 'Theni'), ('TH3', 'Thoothukudi'), ('TI', 'Tiruchirappalli'), ('TI2', 'Tirunelveli'), ('TI3', 'Tirupathur'), ('TI4', 'Tiruppur'), ('TI5', 'Tiruvallur'), ('TI6', 'Tiruvannamalai'), ('TV', 'Tiruvarur'), ('VE', 'Vellore'), ('VI', 'Viluppuram'), ('VI2', 'Virudhunagar'), ('AL', 'Alappuzha'), ('ER', 'Ernakulam'), ('ID', 'Idukki'), ('KA', 'Kannur'), ('KA2', 'Kasaragod'), ('KO', 'Kollam'), ('KO2', 'Kottayam'), ('KO3', 'Kozhikode'), ('MA', 'Malappuram'), ('PA', 'Palakkad'), ('PA2', 'Pathanamthitta'), ('TH', 'Thiruvananthapuram'), ('TH2', 'Thrissur'), ('WA', 'Wayanad')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagementmodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagementmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermanagementmodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagementmodel',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='usermanagementmodel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=core.filepath.hash_profile),
        ),
        migrations.AlterField(
            model_name='usermanagementmodel',
            name='state',
            field=models.CharField(blank=True, choices=[('TN', 'Tamil Nadu'), ('KL', 'Kerala')], max_length=50),
        ),
        migrations.CreateModel(
            name='OTPVerifyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('otp_max_try', models.CharField(default=3, max_length=2)),
                ('otp_max_out', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
