# Generated by Django 4.1 on 2025-02-20 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customermodel_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverifymodel',
            name='is_otp_verified',
        ),
        migrations.AddField(
            model_name='deliveryboymodel',
            name='is_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellermodel',
            name='is_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deliveryboymodel',
            name='file_license',
            field=models.FileField(default=django.utils.timezone.now, upload_to='files/licence/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='file_gst',
            field=models.FileField(default=django.utils.timezone.now, upload_to='files/gst/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='file_pan',
            field=models.FileField(default=django.utils.timezone.now, upload_to='files/pan/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermanagementmodel',
            name='profile_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile/'),
            preserve_default=False,
        ),
    ]
