# Generated by Django 4.1 on 2025-02-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_deliveryboymodel_user_alter_sellermodel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='is_otp',
            field=models.BooleanField(default=False),
        ),
    ]
