# Generated by Django 5.1.6 on 2025-02-21 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customermodel_is_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryboymodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveryboy_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
