# Generated by Django 5.1.6 on 2025-02-21 17:39

import core.filepath
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customermodel_user_alter_deliveryboymodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboymodel',
            name='file_license',
            field=models.FileField(upload_to=core.filepath.hash_license),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='file_gst',
            field=models.FileField(upload_to=core.filepath.hash_document),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='file_pan',
            field=models.FileField(upload_to=core.filepath.hash_document),
        ),
        migrations.AlterField(
            model_name='usermanagementmodel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=core.filepath.hash_profile),
        ),
    ]
