# Generated by Django 5.1.6 on 2025-02-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_deliveryboymodel_file_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverifymodel',
            name='otp_max_try',
            field=models.IntegerField(default=3, max_length=2),
        ),
    ]
