# Generated by Django 5.1.6 on 2025-02-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_otpverifymodel_otp_max_try'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverifymodel',
            name='otp_max_try',
            field=models.CharField(default=3, max_length=2),
        ),
    ]
