# Generated by Django 5.1.6 on 2025-02-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_otpverifymodel_otp_max_try'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellermodel',
            name='GST_expiry_date',
        ),
    ]
