# Generated by Django 5.1.6 on 2025-02-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_sellermodel_gst_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermanagementmodel',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
