# Generated by Django 5.1.6 on 2025-03-19 05:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customermodel_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellermodel',
            name='GST_expiry_date',
            field=models.DateField(default=accounts.models.default_gst_expiry),
        ),
    ]
