# Generated by Django 5.1.6 on 2025-05-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_sellermodel_gst_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagementmodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagementmodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
