# Generated by Django 5.1.6 on 2025-03-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartmodel_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
