# Generated by Django 5.1.6 on 2025-05-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_ordermodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='product',
            field=models.JSONField(default=dict),
        ),
    ]
