# Generated by Django 5.1.6 on 2025-05-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_ordermodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_status',
            field=models.CharField(choices=[('P', 'Pending'), ('OC', 'Order Confirmed'), ('S', 'Shipped'), ('O', 'Out for Delivery'), ('D', 'Delivered'), ('C', 'Cancelled')], max_length=10),
        ),
    ]
