# Generated by Django 5.1.6 on 2025-05-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image_id',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_category',
            field=models.CharField(blank=True, choices=[('GROCERY', 'Grocery'), ('FOOD', 'Food'), ('DESSERTS', 'Desserts')], max_length=50, null=True),
        ),
    ]
