# Generated by Django 5.1.6 on 2025-03-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productmodel_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
