# Generated by Django 5.1.6 on 2025-05-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productmodel_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='color',
        ),
    ]
